### ISSUE TITLE
Fix SQLite3::BusyException

### ISSUE THREAD

**Issue by dwilkie** [somleng/somleng-scfm#43]
```
ActiveRecord::StatementInvalid: SQLite3::BusyException: database is locked: UPDATE "phone_calls" SET "status" = 'queued', "remote_call_id" = 'dbb45618-ff35-471b-925a-52ca567afd82', "remote_direction" = 'outbound-api', "updated_at" = '2017-10-18 09:24:08.219645', "lock_version" = 1 WHERE "phone_calls"."id" = ? AND "phone_calls"."lock_version" = ?
```

/usr/src/app/app/tasks/enqueue_calls_task.rb:58:in `schedule_phone_call!'
/usr/src/app/app/tasks/enqueue_calls_task.rb:22:in `block in run!'

**Comment by dwilkie** [comment]
https://stackoverflow.com/questions/7154664/ruby-sqlite3busyexception-database-is-locked
